apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-app
